### PR TITLE
Juptyer notebook for distance/covariance/correlation tutorial

### PR DESCRIPTION
**Pull request by paxtonfitzpatrick**
added an equivalent Python version of [this walkthrough](https://torwager.github.io/ComputationalFoundations/basicdistancecovcorr.html).

I intentionally tried to make it as similar as possible to the MATLAB version both technically (i.e., every line of code in one version has an equivalent in the other, kept variable names & comments identical, etc.) and visually (i.e., plots are styled to match the MATLAB version as closely as possible, code cell outputs should for the most part match, etc.) but there are some small differences. 

Other changes in this version include:
- centered LaTeX equations horizontally and fixed some matrix formatting
- fixed vertical alignment in LaTeX equations and side-by-side formula environments
- re-styled some variables in the markdown text sections with in-line LaTeX to make correspondence with equations clearer
- equated $X^\prime$ to $X^T$ the first few times it's mentioned in the text, since equations use the two interchangeably
- added some informative notes in code comments where differences from MATLAB version exist
- fixed some assorted typos throughout

I've never worked with Jupyter Book before, so I'm not sure where exactly in the repo I should put this for it to be run when the site is built or appear wherever you'd like it to on the course website, so I've just added it to the main directory for now. Also not sure whether certain config files files would need to be edited to make that happen.

Also, in case this is needed for it to run correctly when the site is built, the environment I created the notebook in had:
- Python v3.10.12 (though anything >=3.7 should be fine)
- `numpy==1.26.0`
- `matplotlib==3.8.0`
- `scipy==1.11.2`
I believe some of the LaTeX also requires the `amsmath` package, but it looks like the repo already has that configured

### CODE REVIEW

**Comment by paxtonfitzpatrick** [comment]
[Here](https://www.dropbox.com/scl/fi/k5c4n3w6bziu9r837fd9v/Basic_principles_Distance_covariance_correlation-Python.html?rlkey=789sfrnvh8t2aiq969jaf3xsq&dl=0) is the notebook exported as an HTML file, in case that's more helpful. Let me know if there's anything you'd like me to change!

**Comment by paxtonfitzpatrick** [comment]
Added my name to the notebook like you mentioned during class. Happy to remove this if you prefer -- just let me know.

**Comment by paxtonfitzpatrick** [comment]
added my notebook from week 2 with a GLM from scratch in Python -- happy to leave it in or remove it 🙂

**Comment by torwager** [comment]
Thanks Patrick! I merged this in. I had to change the kernel name to python3 here, in 2 ipynb files:

 "metadata": {
  "kernelspec": {
   "display_name": "psyc178",
   "language": "python",
   "name": "psyc178"
  },

The GLM script has some code that doesn't seem to work (maybe my jupyter-book format/installed modules? one error was in loading numpy).
tor

**Pull request merged**
